import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/db";

export const dynamic = "force-dynamic";

export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const difficulty = searchParams.get("difficulty") || "easy";

    // Get current date in YYYY-MM-DD format
    const today = new Date().toISOString().split("T")[0];

    // Try to get existing puzzle for today
    let puzzle = await prisma.dailyPuzzle.findFirst({
      where: {
        date: today,
        difficulty,
      },
    });

    // If no puzzle exists, return 404 (puzzles are pre-generated by script)
    if (!puzzle) {
      return NextResponse.json(
        { error: "Puzzle not available. Please try again later." },
        { status: 404 }
      );
    }

    return NextResponse.json(puzzle);
  } catch (error) {
    console.error("Error fetching daily puzzle:", error);
    return NextResponse.json(
      { error: "Failed to fetch daily puzzle" },
      { status: 500 }
    );
  }
}
